export const GET_MOVIES = "GET_MOVIES"
export const GET_DETAIL = "GET_DETAIL"
export const GET_NAME = "GET_NAME"
export const GET_MOVIES_BY_GENRE = "GET_MOVIES_BY_GENRE"
export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART =  "REMOVE_FROM_CART"